# Generated by Django 4.0 on 2021-12-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yammiback', '0002_myuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
