# Generated by Django 4.0 on 2021-12-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yammiback', '0003_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.IntegerField(default=500),
        ),
    ]
